### ISSUE TITLE
Keyboard unusable on macOS

### ISSUE THREAD

**Issue by TheBaronHimself** [keyboardio/KeyboardioHID#18]
Recent versions of the firmware render my Model01 unusable on macOS (10.13.1). It doesn't send any keys, and LED functions (such as https://github.com/keyboardio/Kaleidoscope-LED-ActiveModColor) react with a considerable delay. The keyboard appears to operate normally under Windows; I haven't tested in on Linux yet, but others don't seem to have any issues there, either.

The latest working commit is fa09374e412f09b7177f3f6e20312be47cdcc961.

**Comment by obra** [comment]
That sounds a lot like the host put the keyboard into low power / slew mode and we didn’t wake up.

**Comment by obra** [comment]
Are you running with the stock sketch?

**Comment by TheBaronHimself** [comment]
Yes, tried my own sketch and the stock sketch - same result for both.

I just realised a distinction I should point out, though: LED effects that are entirely keyboard-internal and not based on any host interaction seem to have worked fine - no delay there. LED-ActiveModColor I'm guessing includes some interaction with the computer it's connected to (haven't looked at the code too much myself), and because that interaction is not working properly, the LED effect isn't, either.

**Comment by algernon** [comment]
`ActiveModColor` relies on reports being set and sent. That likely doesn't happen (hence the keyboard not working either).

**Comment by TheBaronHimself** [comment]
Yeah, that's what I thought. Thanks for confirming.
