### ISSUE TITLE
'class HID_' has no member named 'getLEDs'

### ISSUE THREAD

**Issue by iLobster** [keyboardio/KeyboardioHID#31]
Using Arduino IDE 1.8.5 (Windows store 1.8.10.0)
Arduino AVR Boards v 1.6.21 (tried 1.6.20, 1.6.19, 16.18)

Trying to compile KeyboardLed.ino from examples and get:

`
C:\Users\iLobster\Documents\Arduino\libraries\KeyboardioHID\src/MultiReport/Keyboard.h:62:36: error: 'class HID_' has no member named 'getLEDs'
`

--- full output:

C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\arduino-builder -dump-prefs -logger=machine -hardware C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\hardware -hardware C:\Users\iLobster\Documents\ArduinoData\packages -hardware C:\Users\iLobster\Documents\Arduino\hardware -tools C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\tools-builder -tools C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\hardware\tools\avr -tools C:\Users\iLobster\Documents\ArduinoData\packages -built-in-libraries C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\libraries -libraries C:\Users\iLobster\Documents\Arduino\libraries -fqbn=HoodLoader2:avr:HoodLoader2atmega16u2:board=uno -ide-version=10805 -build-path C:\Users\iLobster\AppData\Local\Temp\arduino_build_535860 -warnings=none -build-cache C:\Users\iLobster\AppData\Local\Temp\arduino_cache_322616 -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.avrdude.path=C:\Users\iLobster\Documents\ArduinoData\packages\arduino\tools\avrdude\6.3.0-arduino9 -prefs=runtime.tools.arduinoOTA.path=C:\Users\iLobster\Documents\ArduinoData\packages\arduino\tools\arduinoOTA\1.1.1 -prefs=runtime.tools.avr-gcc.path=C:\Users\iLobster\Documents\ArduinoData\packages\arduino\tools\avr-gcc\4.9.2-atmel3.5.4-arduino2 -verbose C:\Users\iLobster\Documents\Arduino\libraries\KeyboardioHID\examples\Keyboard\KeyboardLed\KeyboardLed.ino
C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\arduino-builder -compile -logger=machine -hardware C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\hardware -hardware C:\Users\iLobster\Documents\ArduinoData\packages -hardware C:\Users\iLobster\Documents\Arduino\hardware -tools C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\tools-builder -tools C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\hardware\tools\avr -tools C:\Users\iLobster\Documents\ArduinoData\packages -built-in-libraries C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\libraries -libraries C:\Users\iLobster\Documents\Arduino\libraries -fqbn=HoodLoader2:avr:HoodLoader2atmega16u2:board=uno -ide-version=10805 -build-path C:\Users\iLobster\AppData\Local\Temp\arduino_build_535860 -warnings=none -build-cache C:\Users\iLobster\AppData\Local\Temp\arduino_cache_322616 -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.avrdude.path=C:\Users\iLobster\Documents\ArduinoData\packages\arduino\tools\avrdude\6.3.0-arduino9 -prefs=runtime.tools.arduinoOTA.path=C:\Users\iLobster\Documents\ArduinoData\packages\arduino\tools\arduinoOTA\1.1.1 -prefs=runtime.tools.avr-gcc.path=C:\Users\iLobster\Documents\ArduinoData\packages\arduino\tools\avr-gcc\4.9.2-atmel3.5.4-arduino2 -verbose C:\Users\iLobster\Documents\Arduino\libraries\KeyboardioHID\examples\Keyboard\KeyboardLed\KeyboardLed.ino
Using board 'HoodLoader2atmega16u2' from platform in folder: C:\Users\iLobster\Documents\Arduino\hardware\HoodLoader2\avr
Using core 'arduino' from platform in folder: C:\Users\iLobster\Documents\ArduinoData\packages\arduino\hardware\avr\1.6.21
Detecting libraries used...
"C:\Users\iLobster\Documents\ArduinoData\packages\arduino\tools\avr-gcc\4.9.2-atmel3.5.4-arduino2/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -flto -w -x c++ -E -CC -mmcu=atmega16u2 -DF_CPU=16000000L -DARDUINO=10805 -DARDUINO_HOODLOADER2 -DARDUINO_ARCH_AVR  -DUSB_VID=0x2341 -DUSB_PID=0x484C '-DUSB_MANUFACTURER="Nico Hood"' '-DUSB_PRODUCT="HoodLoader2 16u2"' -DMAGIC_KEY_POS=(RAMEND-1) -DUSB_EP_SIZE=16 "-IC:\Users\iLobster\Documents\ArduinoData\packages\arduino\hardware\avr\1.6.21\cores\arduino" "-IC:\Users\iLobster\Documents\Arduino\hardware\HoodLoader2\avr\variants\HoodLoader2" "C:\Users\iLobster\AppData\Local\Temp\arduino_build_535860\sketch\KeyboardLed.ino.cpp" -o "nul"
"C:\Users\iLobster\Documents\ArduinoData\packages\arduino\tools\avr-gcc\4.9.2-atmel3.5.4-arduino2/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -flto -w -x c++ -E -CC -mmcu=atmega16u2 -DF_CPU=16000000L -DARDUINO=10805 -DARDUINO_HOODLOADER2 -DARDUINO_ARCH_AVR  -DUSB_VID=0x2341 -DUSB_PID=0x484C '-DUSB_MANUFACTURER="Nico Hood"' '-DUSB_PRODUCT="HoodLoader2 16u2"' -DMAGIC_KEY_POS=(RAMEND-1) -DUSB_EP_SIZE=16 "-IC:\Users\iLobster\Documents\ArduinoData\packages\arduino\hardware\avr\1.6.21\cores\arduino" "-IC:\Users\iLobster\Documents\Arduino\hardware\HoodLoader2\avr\variants\HoodLoader2" "-IC:\Users\iLobster\Documents\Arduino\libraries\KeyboardioHID\src" "C:\Users\iLobster\AppData\Local\Temp\arduino_build_535860\sketch\KeyboardLed.ino.cpp" -o "nul"
"C:\Users\iLobster\Documents\ArduinoData\packages\arduino\tools\avr-gcc\4.9.2-atmel3.5.4-arduino2/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -flto -w -x c++ -E -CC -mmcu=atmega16u2 -DF_CPU=16000000L -DARDUINO=10805 -DARDUINO_HOODLOADER2 -DARDUINO_ARCH_AVR  -DUSB_VID=0x2341 -DUSB_PID=0x484C '-DUSB_MANUFACTURER="Nico Hood"' '-DUSB_PRODUCT="HoodLoader2 16u2"' -DMAGIC_KEY_POS=(RAMEND-1) -DUSB_EP_SIZE=16 "-IC:\Users\iLobster\Documents\ArduinoData\packages\arduino\hardware\avr\1.6.21\cores\arduino" "-IC:\Users\iLobster\Documents\Arduino\hardware\HoodLoader2\avr\variants\HoodLoader2" "-IC:\Users\iLobster\Documents\Arduino\libraries\KeyboardioHID\src" "-IC:\Users\iLobster\Documents\ArduinoData\packages\arduino\hardware\avr\1.6.21\libraries\HID\src" "C:\Users\iLobster\AppData\Local\Temp\arduino_build_535860\sketch\KeyboardLed.ino.cpp" -o "nul"
"C:\Users\iLobster\Documents\ArduinoData\packages\arduino\tools\avr-gcc\4.9.2-atmel3.5.4-arduino2/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -flto -w -x c++ -E -CC -mmcu=atmega16u2 -DF_CPU=16000000L -DARDUINO=10805 -DARDUINO_HOODLOADER2 -DARDUINO_ARCH_AVR  -DUSB_VID=0x2341 -DUSB_PID=0x484C '-DUSB_MANUFACTURER="Nico Hood"' '-DUSB_PRODUCT="HoodLoader2 16u2"' -DMAGIC_KEY_POS=(RAMEND-1) -DUSB_EP_SIZE=16 "-IC:\Users\iLobster\Documents\ArduinoData\packages\arduino\hardware\avr\1.6.21\cores\arduino" "-IC:\Users\iLobster\Documents\Arduino\hardware\HoodLoader2\avr\variants\HoodLoader2" "-IC:\Users\iLobster\Documents\Arduino\libraries\KeyboardioHID\src" "-IC:\Users\iLobster\Documents\ArduinoData\packages\arduino\hardware\avr\1.6.21\libraries\HID\src" "C:\Users\iLobster\Documents\Arduino\libraries\KeyboardioHID\src\BootKeyboard\BootKeyboard.cpp" -o "nul"
"C:\Users\iLobster\Documents\ArduinoData\packages\arduino\tools\avr-gcc\4.9.2-atmel3.5.4-arduino2/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -flto -w -x c++ -E -CC -mmcu=atmega16u2 -DF_CPU=16000000L -DARDUINO=10805 -DARDUINO_HOODLOADER2 -DARDUINO_ARCH_AVR  -DUSB_VID=0x2341 -DUSB_PID=0x484C '-DUSB_MANUFACTURER="Nico Hood"' '-DUSB_PRODUCT="HoodLoader2 16u2"' -DMAGIC_KEY_POS=(RAMEND-1) -DUSB_EP_SIZE=16 "-IC:\Users\iLobster\Documents\ArduinoData\packages\arduino\hardware\avr\1.6.21\cores\arduino" "-IC:\Users\iLobster\Documents\Arduino\hardware\HoodLoader2\avr\variants\HoodLoader2" "-IC:\Users\iLobster\Documents\Arduino\libraries\KeyboardioHID\src" "-IC:\Users\iLobster\Documents\ArduinoData\packages\arduino\hardware\avr\1.6.21\libraries\HID\src" "C:\Users\iLobster\Documents\Arduino\libraries\KeyboardioHID\src\MultiReport\AbsoluteMouse.cpp" -o "nul"
"C:\Users\iLobster\Documents\ArduinoData\packages\arduino\tools\avr-gcc\4.9.2-atmel3.5.4-arduino2/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -flto -w -x c++ -E -CC -mmcu=atmega16u2 -DF_CPU=16000000L -DARDUINO=10805 -DARDUINO_HOODLOADER2 -DARDUINO_ARCH_AVR  -DUSB_VID=0x2341 -DUSB_PID=0x484C '-DUSB_MANUFACTURER="Nico Hood"' '-DUSB_PRODUCT="HoodLoader2 16u2"' -DMAGIC_KEY_POS=(RAMEND-1) -DUSB_EP_SIZE=16 "-IC:\Users\iLobster\Documents\ArduinoData\packages\arduino\hardware\avr\1.6.21\cores\arduino" "-IC:\Users\iLobster\Documents\Arduino\hardware\HoodLoader2\avr\variants\HoodLoader2" "-IC:\Users\iLobster\Documents\Arduino\libraries\KeyboardioHID\src" "-IC:\Users\iLobster\Documents\ArduinoData\packages\arduino\hardware\avr\1.6.21\libraries\HID\src" "C:\Users\iLobster\Documents\Arduino\libraries\KeyboardioHID\src\MultiReport\ConsumerControl.cpp" -o "nul"
"C:\Users\iLobster\Documents\ArduinoData\packages\arduino\tools\avr-gcc\4.9.2-atmel3.5.4-arduino2/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -flto -w -x c++ -E -CC -mmcu=atmega16u2 -DF_CPU=16000000L -DARDUINO=10805 -DARDUINO_HOODLOADER2 -DARDUINO_ARCH_AVR  -DUSB_VID=0x2341 -DUSB_PID=0x484C '-DUSB_MANUFACTURER="Nico Hood"' '-DUSB_PRODUCT="HoodLoader2 16u2"' -DMAGIC_KEY_POS=(RAMEND-1) -DUSB_EP_SIZE=16 "-IC:\Users\iLobster\Documents\ArduinoData\packages\arduino\hardware\avr\1.6.21\cores\arduino" "-IC:\Users\iLobster\Documents\Arduino\hardware\HoodLoader2\avr\variants\HoodLoader2" "-IC:\Users\iLobster\Documents\Arduino\libraries\KeyboardioHID\src" "-IC:\Users\iLobster\Documents\ArduinoData\packages\arduino\hardware\avr\1.6.21\libraries\HID\src" "C:\Users\iLobster\Documents\Arduino\libraries\KeyboardioHID\src\MultiReport\Gamepad.cpp" -o "nul"
"C:\Users\iLobster\Documents\ArduinoData\packages\arduino\tools\avr-gcc\4.9.2-atmel3.5.4-arduino2/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -flto -w -x c++ -E -CC -mmcu=atmega16u2 -DF_CPU=16000000L -DARDUINO=10805 -DARDUINO_HOODLOADER2 -DARDUINO_ARCH_AVR  -DUSB_VID=0x2341 -DUSB_PID=0x484C '-DUSB_MANUFACTURER="Nico Hood"' '-DUSB_PRODUCT="HoodLoader2 16u2"' -DMAGIC_KEY_POS=(RAMEND-1) -DUSB_EP_SIZE=16 "-IC:\Users\iLobster\Documents\ArduinoData\packages\arduino\hardware\avr\1.6.21\cores\arduino" "-IC:\Users\iLobster\Documents\Arduino\hardware\HoodLoader2\avr\variants\HoodLoader2" "-IC:\Users\iLobster\Documents\Arduino\libraries\KeyboardioHID\src" "-IC:\Users\iLobster\Documents\ArduinoData\packages\arduino\hardware\avr\1.6.21\libraries\HID\src" "C:\Users\iLobster\Documents\Arduino\libraries\KeyboardioHID\src\MultiReport\Keyboard.cpp" -o "nul"
"C:\Users\iLobster\Documents\ArduinoData\packages\arduino\tools\avr-gcc\4.9.2-atmel3.5.4-arduino2/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -flto -w -x c++ -E -CC -mmcu=atmega16u2 -DF_CPU=16000000L -DARDUINO=10805 -DARDUINO_HOODLOADER2 -DARDUINO_ARCH_AVR  -DUSB_VID=0x2341 -DUSB_PID=0x484C '-DUSB_MANUFACTURER="Nico Hood"' '-DUSB_PRODUCT="HoodLoader2 16u2"' -DMAGIC_KEY_POS=(RAMEND-1) -DUSB_EP_SIZE=16 "-IC:\Users\iLobster\Documents\ArduinoData\packages\arduino\hardware\avr\1.6.21\cores\arduino" "-IC:\Users\iLobster\Documents\Arduino\hardware\HoodLoader2\avr\variants\HoodLoader2" "-IC:\Users\iLobster\Documents\Arduino\libraries\KeyboardioHID\src" "-IC:\Users\iLobster\Documents\ArduinoData\packages\arduino\hardware\avr\1.6.21\libraries\HID\src" "C:\Users\iLobster\Documents\Arduino\libraries\KeyboardioHID\src\MultiReport\Mouse.cpp" -o "nul"
"C:\Users\iLobster\Documents\ArduinoData\packages\arduino\tools\avr-gcc\4.9.2-atmel3.5.4-arduino2/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -flto -w -x c++ -E -CC -mmcu=atmega16u2 -DF_CPU=16000000L -DARDUINO=10805 -DARDUINO_HOODLOADER2 -DARDUINO_ARCH_AVR  -DUSB_VID=0x2341 -DUSB_PID=0x484C '-DUSB_MANUFACTURER="Nico Hood"' '-DUSB_PRODUCT="HoodLoader2 16u2"' -DMAGIC_KEY_POS=(RAMEND-1) -DUSB_EP_SIZE=16 "-IC:\Users\iLobster\Documents\ArduinoData\packages\arduino\hardware\avr\1.6.21\cores\arduino" "-IC:\Users\iLobster\Documents\Arduino\hardware\HoodLoader2\avr\variants\HoodLoader2" "-IC:\Users\iLobster\Documents\Arduino\libraries\KeyboardioHID\src" "-IC:\Users\iLobster\Documents\ArduinoData\packages\arduino\hardware\avr\1.6.21\libraries\HID\src" "C:\Users\iLobster\Documents\Arduino\libraries\KeyboardioHID\src\MultiReport\SystemControl.cpp" -o "nul"
"C:\Users\iLobster\Documents\ArduinoData\packages\arduino\tools\avr-gcc\4.9.2-atmel3.5.4-arduino2/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -flto -w -x c++ -E -CC -mmcu=atmega16u2 -DF_CPU=16000000L -DARDUINO=10805 -DARDUINO_HOODLOADER2 -DARDUINO_ARCH_AVR  -DUSB_VID=0x2341 -DUSB_PID=0x484C '-DUSB_MANUFACTURER="Nico Hood"' '-DUSB_PRODUCT="HoodLoader2 16u2"' -DMAGIC_KEY_POS=(RAMEND-1) -DUSB_EP_SIZE=16 "-IC:\Users\iLobster\Documents\ArduinoData\packages\arduino\hardware\avr\1.6.21\cores\arduino" "-IC:\Users\iLobster\Documents\Arduino\hardware\HoodLoader2\avr\variants\HoodLoader2" "-IC:\Users\iLobster\Documents\Arduino\libraries\KeyboardioHID\src" "-IC:\Users\iLobster\Documents\ArduinoData\packages\arduino\hardware\avr\1.6.21\libraries\HID\src" "C:\Users\iLobster\Documents\Arduino\libraries\KeyboardioHID\src\SingleReport\SingleAbsoluteMouse.cpp" -o "nul"
"C:\Users\iLobster\Documents\ArduinoData\packages\arduino\tools\avr-gcc\4.9.2-atmel3.5.4-arduino2/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -flto -w -x c++ -E -CC -mmcu=atmega16u2 -DF_CPU=16000000L -DARDUINO=10805 -DARDUINO_HOODLOADER2 -DARDUINO_ARCH_AVR  -DUSB_VID=0x2341 -DUSB_PID=0x484C '-DUSB_MANUFACTURER="Nico Hood"' '-DUSB_PRODUCT="HoodLoader2 16u2"' -DMAGIC_KEY_POS=(RAMEND-1) -DUSB_EP_SIZE=16 "-IC:\Users\iLobster\Documents\ArduinoData\packages\arduino\hardware\avr\1.6.21\cores\arduino" "-IC:\Users\iLobster\Documents\Arduino\hardware\HoodLoader2\avr\variants\HoodLoader2" "-IC:\Users\iLobster\Documents\Arduino\libraries\KeyboardioHID\src" "-IC:\Users\iLobster\Documents\ArduinoData\packages\arduino\hardware\avr\1.6.21\libraries\HID\src" "C:\Users\iLobster\Documents\ArduinoData\packages\arduino\hardware\avr\1.6.21\libraries\HID\src\HID.cpp" -o "nul"
Generating function prototypes...
"C:\Users\iLobster\Documents\ArduinoData\packages\arduino\tools\avr-gcc\4.9.2-atmel3.5.4-arduino2/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics  -flto -w -x c++ -E -CC -mmcu=atmega16u2 -DF_CPU=16000000L -DARDUINO=10805 -DARDUINO_HOODLOADER2 -DARDUINO_ARCH_AVR  -DUSB_VID=0x2341 -DUSB_PID=0x484C '-DUSB_MANUFACTURER="Nico Hood"' '-DUSB_PRODUCT="HoodLoader2 16u2"' -DMAGIC_KEY_POS=(RAMEND-1) -DUSB_EP_SIZE=16 "-IC:\Users\iLobster\Documents\ArduinoData\packages\arduino\hardware\avr\1.6.21\cores\arduino" "-IC:\Users\iLobster\Documents\Arduino\hardware\HoodLoader2\avr\variants\HoodLoader2" "-IC:\Users\iLobster\Documents\Arduino\libraries\KeyboardioHID\src" "-IC:\Users\iLobster\Documents\ArduinoData\packages\arduino\hardware\avr\1.6.21\libraries\HID\src" "C:\Users\iLobster\AppData\Local\Temp\arduino_build_535860\sketch\KeyboardLed.ino.cpp" -o "C:\Users\iLobster\AppData\Local\Temp\arduino_build_535860\preproc\ctags_target_for_gcc_minus_e.cpp"
"C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.10.0_x86__mdqgnx93n4wtt\tools-builder\ctags\5.8-arduino11/ctags" -u --language-force=c++ -f - --c++-kinds=svpf --fields=KSTtzns --line-directives "C:\Users\iLobster\AppData\Local\Temp\arduino_build_535860\preproc\ctags_target_for_gcc_minus_e.cpp"
Compiling sketch...
"C:\Users\iLobster\Documents\ArduinoData\packages\arduino\tools\avr-gcc\4.9.2-atmel3.5.4-arduino2/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -flto -mmcu=atmega16u2 -DF_CPU=16000000L -DARDUINO=10805 -DARDUINO_HOODLOADER2 -DARDUINO_ARCH_AVR  -DUSB_VID=0x2341 -DUSB_PID=0x484C '-DUSB_MANUFACTURER="Nico Hood"' '-DUSB_PRODUCT="HoodLoader2 16u2"' -DMAGIC_KEY_POS=(RAMEND-1) -DUSB_EP_SIZE=16 "-IC:\Users\iLobster\Documents\ArduinoData\packages\arduino\hardware\avr\1.6.21\cores\arduino" "-IC:\Users\iLobster\Documents\Arduino\hardware\HoodLoader2\avr\variants\HoodLoader2" "-IC:\Users\iLobster\Documents\Arduino\libraries\KeyboardioHID\src" "-IC:\Users\iLobster\Documents\ArduinoData\packages\arduino\hardware\avr\1.6.21\libraries\HID\src" "C:\Users\iLobster\AppData\Local\Temp\arduino_build_535860\sketch\KeyboardLed.ino.cpp" -o "C:\Users\iLobster\AppData\Local\Temp\arduino_build_535860\sketch\KeyboardLed.ino.cpp.o"
In file included from C:\Users\iLobster\Documents\Arduino\libraries\KeyboardioHID\src/KeyboardioHID.h:48:0,

                 from C:\Users\iLobster\Documents\Arduino\libraries\KeyboardioHID\examples\Keyboard\KeyboardLed\KeyboardLed.ino:15:

C:\Users\iLobster\Documents\Arduino\libraries\KeyboardioHID\src/MultiReport/Keyboard.h: In member function 'uint8_t Keyboard_::getLEDs()':

C:\Users\iLobster\Documents\Arduino\libraries\KeyboardioHID\src/MultiReport/Keyboard.h:62:36: error: 'class HID_' has no member named 'getLEDs'

   uint8_t getLEDs() { return HID().getLEDs(); };

                                    ^

Using library KeyboardioHID at version 0.0.1 in folder: C:\Users\iLobster\Documents\Arduino\libraries\KeyboardioHID 
Using library HID at version 1.0 in folder: C:\Users\iLobster\Documents\ArduinoData\packages\arduino\hardware\avr\1.6.21\libraries\HID 
exit status 1
Error compiling for board HoodLoader2 16u2.

**Comment by algernon** [comment]
Looking at the logs you provided, in particular this part: `-mmcu=atmega16u2`, it looks like you do not have the board set to `Keyboardio Model 01` in your IDE (the Model01 uses `atmega32u4`, and uses a set of flags missing from your logs). For the example to work, you'll need to set the board appropriately, otherwise Arduino will not include the right variant of the headers.
