### ISSUE TITLE
All supported keyboards register as kbio01

### ISSUE THREAD

**Issue by noseglasses** [keyboardio/KeyboardioHID#54]
Currently all keyboards with description in library Keyboardio use KeyboardioHID. They are all registered as `kbio01`.

https://github.com/keyboardio/KeyboardioHID/blob/921092a5353ddb926784d19940186fb4f0ec2ad6/src/HID.cpp#L68-L76

**Comment by obra** [comment]
*laugh* You're totally right. That should totally get fixed.

**Comment by noseglasses** [comment]
@algernon & @obra can we somehow make this information available through the device implementation?

**Comment by algernon** [comment]
If we manage to pull `KeyboardioHID` into Kaleidoscope as a proper driver (#59), then yes, we can. Otherwise, I don't think so.

**Comment by noseglasses** [comment]
Couldn't we simply declare `uint8_t HID_::getShortName(char *name)` a weak symbol and override it in, `kaleidoscope_internal/device.cpp` based on the device settings?

**Comment by algernon** [comment]
Oh, we could, indeed. I'll do that.

**Comment by algernon** [comment]
Hm. We have a problem: link order. Arduino links Kaleidoscope _first_, KeyboardioHID after. Thus, the overridden symbol in Kaleidoscope does not get used. If we specify it in the sketch, that'd work, but that's not a solution at all.

**Comment by noseglasses** [comment]
That's another occasion where it would really be beneficial to have Arduino add a define `-DSKETCH_COMPILATION_UNIT` or such. That would solve a lot of problems as one could conditionally add code to the sketch compilation just via an include like `Kaleidoscope.h` without requiring a macro for that and be sure that it is linked first.

I already had, for testing purposes, implemented a wrapper compiler that reliably does this. But that's not a general solution as not available if the firmware is build with the Arduino SDK.

An actual solution could be to use a macro that is invoked by `KEYMAPS(...)` under the hood and that implements the non-weak symbol. We already [do that](https://github.com/keyboardio/Kaleidoscope/blob/master/src/kaleidoscope/layers.h) with `_INIT_SKETCH_EXPLORATION`.

**Comment by algernon** [comment]
> That's another occasion where it would really be beneficial to have Arduino add a define `-DSKETCH_COMPILATION_UNIT` or such. That would solve a lot of problems as one could conditionally add code to the sketch compilation just via an include like `Kaleidoscope.h` without requiring a macro for that and be sure that it is linked first.
> 
> I already had, for testing purposes, implemented a wrapper compiler that reliably does this. But that's not a general solution as not available if the firmware is build with the Arduino SDK.
> 
> An actual solution could be to use a macro that is invoked by `KEYMAPS(...)` under the hood and that implements the non-weak symbol. We already [do that](https://github.com/keyboardio/Kaleidoscope/blob/master/src/kaleidoscope/layers.h) with `_INIT_SKETCH_EXPLORATION`.

I'll look into this later, thanks!

**Comment by obra** [comment]
My bad solution for this was going to be to get them to register as
"kaleidoscope" instead of kbio01" But I'm very happy to have something
better.
ᐧ
